### ISSUE TITLE
FayeRails.server nil in production

### ISSUE THREAD

**Issue by nilbus** [jamesotron/faye-rails#27]
When Rails eager-loads my Faye controller, `FayeRails.server(endpoint)` is returning nil in the production environment, which prevents the server from starting.

    /home/nilbus/.bundler/ruby/1.9.1/faye-rails-72639229f67e/lib/faye-rails/controller/channel.rb:23:in `monitor': undefined method `bind' for nil:NilClass (NoMethodError)
        from /home/nilbus/Dropbox/git/pinewood-derby/app/controllers/announce_controller.rb:35:in `block in <class:AnnounceController>'
        from /home/nilbus/.bundler/ruby/1.9.1/faye-rails-72639229f67e/lib/faye-rails/controller.rb:34:in `instance_eval'
        from /home/nilbus/.bundler/ruby/1.9.1/faye-rails-72639229f67e/lib/faye-rails/controller.rb:34:in `channel'
        from /home/nilbus/Dropbox/git/pinewood-derby/app/controllers/announce_controller.rb:34:in `<class:AnnounceController>'
        from /home/nilbus/Dropbox/git/pinewood-derby/app/controllers/announce_controller.rb:1:in `<top (required)>'
        from /home/nilbus/Dropbox/git/rails/activesupport/lib/active_support/dependencies.rb:228:in `require'
        ...
        from /home/nilbus/Dropbox/git/rails/railties/lib/rails/engine.rb:466:in `block (2 levels) in eager_load!'

The relevant part of my AnnounceController:

    class AnnounceController < FayeRails::Controller
      channel '/announce' do
        monitor :publish do
          ApplicationHelper.log "Client #{client_id} published #{data.inspect} to #{channel}."
        end
      end
    end

The line below in [channel.rb](https://github.com/jamesotron/faye-rails/blob/master/lib/faye-rails/controller/channel.rb#L23) is where the traceback is thrown from.

        FayeRails.server(endpoint).bind(event) do |*args|

I'm unsure whether or not this is related to Rails 4.

Is this working in other apps in the production environment?

**Comment by nilbus** [comment]
Everything seems to be working fine now with faye-rails-2.0.0 and Rails 4.

If anyone hits this again in 2.x, feel free to re-open.
