### ISSUE TITLE
Cannot run RSpec specs with Ruby 2.2

### ISSUE THREAD

**Issue by ciastek** [jamesotron/faye-rails#79]
```
vagrant@vagrant-ubuntu-trusty-32:/vagrant$ bundle exec rspec spec
/home/vagrant/.rvm/gems/ruby-2.2.2/gems/activesupport-3.2.21/lib/active_support/values/time_zone.rb:270: warning: circular argument reference - now
/home/vagrant/.rvm/gems/ruby-2.2.2/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require': cannot load such file -- minitest (LoadError)
	from /home/vagrant/.rvm/gems/ruby-2.2.2/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `block in require'
	from /home/vagrant/.rvm/gems/ruby-2.2.2/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:236:in `load_dependency'
	from /home/vagrant/.rvm/gems/ruby-2.2.2/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
	from /vagrant/spec/dummy/spec/spec_helper.rb:4:in `<top (required)>'
	from /vagrant/spec/spec_helper.rb:7:in `require'
	from /vagrant/spec/spec_helper.rb:7:in `block in <top (required)>'
	from /vagrant/spec/spec_helper.rb:7:in `each'
	from /vagrant/spec/spec_helper.rb:7:in `<top (required)>'
	from /vagrant/spec/filter_spec.rb:1:in `require'
	from /vagrant/spec/filter_spec.rb:1:in `<top (required)>'
	from /home/vagrant/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.2.3/lib/rspec/core/configuration.rb:1226:in `load'
	from /home/vagrant/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.2.3/lib/rspec/core/configuration.rb:1226:in `block in load_spec_files'
	from /home/vagrant/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.2.3/lib/rspec/core/configuration.rb:1224:in `each'
	from /home/vagrant/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.2.3/lib/rspec/core/configuration.rb:1224:in `load_spec_files'
	from /home/vagrant/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:97:in `setup'
	from /home/vagrant/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:85:in `run'
	from /home/vagrant/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:70:in `run'
	from /home/vagrant/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:38:in `invoke'
	from /home/vagrant/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.2.3/exe/rspec:4:in `<top (required)>'
	from /home/vagrant/.rvm/gems/ruby-2.2.2/bin/rspec:23:in `load'
	from /home/vagrant/.rvm/gems/ruby-2.2.2/bin/rspec:23:in `<main>'
	from /home/vagrant/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `eval'
	from /home/vagrant/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by ciastek** [comment]
Guessing that Rails 3.1 (used by dummy app) does not support Ruby 2.2.
